# Generated by Django 2.2.5 on 2019-10-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=255)),
                ('cpf', models.CharField(blank=True, db_column='cpf', default=None, max_length=11, null=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='data_nascimento', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuários',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
                'ordering': ('id',),
            },
        ),
    ]
